#!/usr/bin/env python3
"""
Главный CLI-скрипт Coding Agent.
Запуск: python coding_agent.py --issue 1 --repo ваш_логин/репозиторий
"""
import argparse
import sys
import os
import time
import json
from datetime import datetime

# ==================== 1. ЗАГРУЗКА И ПРОВЕРКА ТОКЕНОВ ====================
# Поддержка всех вариантов имен переменных
GITHUB_TOKEN = os.getenv("GH_PAT") or os.getenv("GITHUB_PAT") or os.getenv("GITHUB_TOKEN")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY") or os.getenv("DEEPSEEK_KEY")

if not GITHUB_TOKEN:
    print("❌ Ошибка: GitHub token not found")
    print("   Доступные переменные:")
    for var in ["GH_PAT", "GITHUB_PAT", "GITHUB_TOKEN"]:
        print(f"   - {var}: {'есть' if os.getenv(var) else 'нет'}")
    sys.exit(1)

if not DEEPSEEK_API_KEY:
    print("❌ Ошибка: DeepSeek API key not found")
    print("   Доступные переменные:")
    for var in ["DEEPSEEK_API_KEY", "DEEPSEEK_KEY"]:
        print(f"   - {var}: {'есть' if os.getenv(var) else 'нет'}")
    sys.exit(1)

print("✅ Токены загружены:")
print(f"   GitHub: {'*' * 8}{GITHUB_TOKEN[-4:] if len(GITHUB_TOKEN) > 8 else ''}")
print(f"   DeepSeek: {'*' * 8}{DEEPSEEK_API_KEY[-4:] if len(DEEPSEEK_API_KEY) > 8 else ''}")

# ==================== 2. НАСТРОЙКА ПУТЕЙ И ИМПОРТОВ ====================
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

try:
    from core.github_client import (
        get_issue_content,
        create_branch,
        apply_code_changes,
        create_pull_request,
        get_latest_ai_review_verdict,
        get_repo_files,
        test_github_connection
    )
    from core.llm_service import analyze_issue_with_llm, generate_code_changes
    print("✅ Модули загружены")
except ImportError as e:
    print(f"❌ Ошибка импорта: {e}")
    print("   Убедитесь, что есть папка 'core' с файлами:")
    print("   - core/github_client.py")
    print("   - core/llm_service.py")
    sys.exit(1)

# ==================== 3. ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ ====================
def prepare_files_from_llm_response(llm_response, attempt_number):
    """Подготавливает файлы для изменения из ответа LLM."""
    files_to_change = {}
    changes = llm_response.get("changes", [])
    
    if not changes:
        print("⚠️ LLM не предложил изменений. Использую шаблон...")
        files_to_change = {
            f"generated_{attempt_number}.py": f"""# Попытка {attempt_number}
# Generated by Coding Agent

def solution():
    \"\"\"Решение созданное Coding Agent.\"\"\"
    return "Hello from Coding Agent!"

if __name__ == "__main__":
    print(solution())
"""
        }
    else:
        for change in changes:
            file_path = change.get("file_path", f"generated_{attempt_number}.py")
            new_content = change.get("new_content", "# Файл создан агентом")
            files_to_change[file_path] = new_content
    
    return files_to_change

def create_issue_comment(repo_full_name, issue_number, message):
    """Создает комментарий в Issue."""
    try:
        from github import Github
        github_client = Github(GITHUB_TOKEN)
        repo = github_client.get_repo(repo_full_name)
        issue = repo.get_issue(number=issue_number)
        issue.create_comment(message)
        print(f"💬 Комментарий добавлен к Issue #{issue_number}")
    except Exception as e:
        print(f"⚠️ Не удалось добавить комментарий: {e}")

# ==================== 4. ОСНОВНАЯ ЛОГИКА АГЕНТА ====================
def main(issue_number, repo_full_name):
    print(f"\n🚀 Запуск Coding Agent для Issue #{issue_number} в {repo_full_name}")
    print("=" * 50)

    # Проверяем подключение к GitHub
    print("🔗 Проверка подключения к GitHub...")
    if not test_github_connection():
        print("❌ Не удалось подключиться к GitHub")
        return None

    MAX_ATTEMPTS = 2  # Уменьшим для теста
    current_attempt = 1
    pr_url = None
    branch_name = f"coding-agent/issue-{issue_number}"

    try:
        # 1. Получаем задачу из Issue
        print("📋 Получение задачи из GitHub...")
        issue_title, issue_body = get_issue_content(repo_full_name, issue_number)
        print(f"   Заголовок: {issue_title}")
        print(f"   Описание: {issue_body[:200]}...")

        # 2. Получаем список файлов в репозитории для контекста
        print("📁 Получение структуры репозитория...")
        repo_files = get_repo_files(repo_full_name)
        if repo_files:
            print(f"   Найдено файлов: {len(repo_files)}")

        while current_attempt <= MAX_ATTEMPTS:
            print(f"\n🔄 ПОПЫТКА {current_attempt}/{MAX_ATTEMPTS}")
            print("-" * 40)

            if current_attempt > 1:
                print("👀 Жду вердикт от AI Reviewer...")
                time.sleep(5)

            # 3. Анализируем задачу с помощью LLM
            print("🧠 Анализ задачи с помощью AI...")
            analysis = analyze_issue_with_llm(issue_title, issue_body, repo_files)
            
            # 4. Генерируем код
            print("💻 Генерация кода...")
            llm_response = generate_code_changes(issue_body, analysis)
            
            print(f"📝 План: {llm_response.get('summary', 'План не указан')}")
            
            # 5. Подготавливаем файлы для изменения
            files_to_change = prepare_files_from_llm_response(llm_response, current_attempt)
            print(f"📄 Файлов для изменения: {len(files_to_change)}")
            for file_path in files_to_change.keys():
                print(f"   - {file_path}")

            # 6. Создаём/обновляем ветку и PR
            commit_message = f"Fix Issue #{issue_number} (attempt {current_attempt}): {issue_title[:50]}..."

            if current_attempt == 1:
                # Первая попытка: создаём новую ветку и PR
                print(f"🌳 Создаю ветку '{branch_name}'...")
                create_branch(repo_full_name, branch_name)

                print(f"📝 Применяю изменения в ветку...")
                apply_code_changes(repo_full_name, branch_name, files_to_change, commit_message)

                print(f"🔗 Создаю Pull Request...")
                pr_url = create_pull_request(repo_full_name, branch_name, issue_title, issue_number)
                if pr_url:
                    print(f"✅ PR создан: {pr_url}")
                else:
                    print("❌ Не удалось создать PR")
                    break
            else:
                # Последующие попытки: обновляем существующий PR
                print(f"✏️ Обновляю существующий PR (попытка {current_attempt})...")
                apply_code_changes(repo_full_name, branch_name, files_to_change, commit_message)
                print(f"✅ Код обновлён в существующем PR: {pr_url}")

            # 7. Извлекаем номер PR из URL
            pr_number = None
            if pr_url:
                try:
                    pr_number = int(pr_url.split("/")[-1])
                except:
                    pass

            # 8. Ждем и проверяем вердикт Reviewer
            if current_attempt == 1:
                print("\n⏳ Жду запуск AI Reviewer... (30 сек)")
                time.sleep(30)

            if pr_number:
                # Проверяем вердикт Reviewer
                print("🤖 Проверяю вердикт AI Reviewer...")
                verdict = get_latest_ai_review_verdict(repo_full_name, pr_number)

                print(f"   Вердикт AI Reviewer: {verdict}")

                if verdict == "APPROVE":
                    print("=" * 50)
                    print(f"🎉 УСПЕХ! Задача решена с {current_attempt} попытки.")
                    print(f"🔗 Pull Request: {pr_url}")
                    
                    # Оставляем комментарий в Issue
                    success_message = f"""
## 🎉 Задача решена!

**Issue #{issue_number} успешно обработана Coding Agent.**

✅ Решение одобрено AI Reviewer
✅ PR создан: {pr_url}
✅ Потребовалось попыток: {current_attempt}

*Автоматическая система SDLC завершила работу успешно.*
"""
                    create_issue_comment(repo_full_name, issue_number, success_message)
                    
                    return pr_url
                elif verdict == "REQUEST_CHANGES":
                    print("⚠️ AI Reviewer запросил исправления. Готовлю новую попытку...")
                    current_attempt += 1
                    continue
                else:
                    print(f"⏳ AI Reviewer: {verdict}. Жду... (20 сек)")
                    time.sleep(20)
                    continue
            else:
                print("❌ Не удалось получить номер PR")
                break

            current_attempt += 1

        # Если вышли из цикла (все попытки исчерпаны)
        print("=" * 50)
        print(f"🚨 ДОСТИГНУТ ЛИМИТ ПОПЫТОК ({MAX_ATTEMPTS})")
        print(f"🔗 Последний PR: {pr_url}")

        # Оставляем комментарий в Issue
        failure_message = f"""
## ⚠️ Coding Agent остановлен

Достигнут лимит в {MAX_ATTEMPTS} попыток.

**Последний статус:**
- Issue: #{issue_number}
- Последний PR: {pr_url or 'не создан'}
- Попыток: {current_attempt-1}

*Пожалуйста, проверьте задачу вручную.*
"""
        create_issue_comment(repo_full_name, issue_number, failure_message)

        return pr_url

    except Exception as e:
        print(f"\n💥 Критическая ошибка:")
        print(f"   Тип: {type(e).__name__}")
        print(f"   Сообщение: {e}")
        
        # Оставляем комментарий об ошибке
        error_message = f"""
## 💥 Ошибка Coding Agent

При обработке Issue #{issue_number} произошла ошибка:

*Пожалуйста, проверьте логи в GitHub Actions.*
"""
        create_issue_comment(repo_full_name, issue_number, error_message)
        
        raise

# ==================== 5. CLI ИНТЕРФЕЙС ====================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='Coding Agent: автоматически создаёт Pull Request для GitHub Issues',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Примеры использования:
  python coding_agent.py --issue 1 --repo username/test-repo
  python coding_agent.py --issue 5 --repo organization/project

Требуемые секреты в GitHub:
  - GH_PAT: GitHub Personal Access Token
  - DEEPSEEK_KEY: DeepSeek API Key
        """
    )

    parser.add_argument(
        '--issue',
        type=int,
        required=True,
        help='Номер Issue в GitHub'
    )

    parser.add_argument(
        '--repo',
        type=str,
        required=True,
        help='Репозиторий в формате "владелец/название"'
    )

    parser.add_argument(
        '--test',
        action='store_true',
        help='Тестовый режим (только анализ без создания PR)'
    )

    args = parser.parse_args()

    if args.test:
        print("🧪 ТЕСТОВЫЙ РЕЖИМ")
        print(f"   Issue: #{args.issue}")
        print(f"   Repo: {args.repo}")
        
        try:
            # Только анализ
            issue_title, issue_body = get_issue_content(args.repo, args.issue)
            print(f"✅ Issue получена: {issue_title}")
            
            analysis = analyze_issue_with_llm(issue_title, issue_body)
            print(f"\n✅ Анализ завершен")
            print(f"   Сложность: {analysis.get('estimated_complexity', 'unknown')}")
            print(f"   Файлов для создания: {len(analysis.get('files_to_create', []))}")
            
            if analysis.get('files_to_create'):
                print("   Файлы:")
                for file in analysis['files_to_create'][:3]:
                    print(f"     - {file}")
        except Exception as e:
            print(f"❌ Ошибка: {e}")
            import traceback
            traceback.print_exc()
    else:
        # Запускаем главную функцию
        result = main(args.issue, args.repo)
        
        if result:
            print(f"\n✅ Coding Agent завершил работу")
            print(f"   Результат: {result}")
            sys.exit(0)
        else:
            print(f"\n❌ Coding Agent завершил работу с ошибкой")
            sys.exit(1)
